Buttons:
  confirm:                                              [1079,857,11,9]
  rebet:                                                [953,856,10,9]
  cancel:                                               [822,852,11,12]

Lobby:
  center:                                               [955,474,10,11]

InGame:
  balance:                                              [265,162,259,43]
  digitalmsg:                                           [790,371,359,65]
  result:                                               [271,454,248,41]
  baccarat:
    player:                                             [572,739,40,29]
    tie:                                                [947,748,36,32]
    banker:                                             [1310,742,47,33]
    player-pair:                                        [684,671,15,11]
    any-pair:                                           [867,668,12,11]
    perfect-pair:                                       [1038,672,12,11]
    banker-pair:                                        [1215,673,13,11]
    player-bonus:                                       [334,722,31,28]
    banker-bonus:                                       [1550,716,11,12]

ImagePath:
  Main:                                                 "\\imgs\\"
  Nav:                                                  "\\imgs\\nav"
  Table:                                                "\\imgs\\tables"
